### ISSUE TITLE
error when i run command vendor/bin/phpunit

### ISSUE THREAD

**Issue by ravisvyas** [emmanuelroecker/php-linkchecker#1]
Mon, 23 Jul 2018 13:26:39 +0000 - Web server started on localhost:1349
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

....FFF

Time: 7.12 seconds, Memory: 7.25MB

There were 3 failures:

1) GlLinkChecker\Tests\GlLinkCheckerTest::testJson
http://lyon.glicer.com/
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'absolute' => true
     'lowercase' => true
-    'exist' => true
+    'exist' => false
     'notendslash' => true
 )

/home/vokunju1/public_html/404checker/tests/GlLinkCheckerTest.php:80
/home/vokunju1/public_html/404checker/tests/GlLinkCheckerTest.php:106

2) GlLinkChecker\Tests\GlLinkCheckerTest::testLinks
http://lyon.glicer.com/
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'absolute' => true
     'lowercase' => true
-    'exist' => true
+    'exist' => false
     'notendslash' => true
 )

/home/vokunju1/public_html/404checker/tests/GlLinkCheckerTest.php:80
/home/vokunju1/public_html/404checker/tests/GlLinkCheckerTest.php:137

3) GlLinkChecker\Tests\GlLinkCheckerTest::testReport
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
                         width: 150px;
-                    }</style></head><body><div class="link"><a href="/index.html">/index.html</a> -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="/section/probleme-solution/compresser-css-html-js.html">/section/probleme-solution/compresser-css-html-js.html</a> -> index.html</div><div class="link"><a href="http://dev.glicer.com/">http://dev.glicer.com/</a> -> index.html</div><div class="link"><a href="http://dev.glicer.com/section/probleme-solution/prefixer-automatiquement-css.html">http://dev.glicer.com/section/probleme-solution/prefixer-automatiquement-css.html</a> -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="http://lyon.glicer.com/">http://lyon.glicer.com/</a> -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="http://stop.glicer.com/no-exist.html" class="error tooltip" data-tooltip="Must exist (Http get error)">http://stop.glicer.com/no-exist.html</a>0 -> index.html</div><br><br><br></body></html>'
+                    }</style></head><body><div class="link"><a href="/index.html">/index.html</a> -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="/section/probleme-solution/compresser-css-html-js.html">/section/probleme-solution/compresser-css-html-js.html</a> -> index.html</div><div class="link"><a href="http://dev.glicer.com/">http://dev.glicer.com/</a> -> index.html</div><div class="link"><a href="http://dev.glicer.com/section/probleme-solution/prefixer-automatiquement-css.html">http://dev.glicer.com/section/probleme-solution/prefixer-automatiquement-css.html</a> -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="http://lyon.glicer.com/" class="error tooltip" data-tooltip="Must exist (Http get error)">http://lyon.glicer.com/</a>0 -> section/probleme-solution/compresser-css-html-js.html</div><div class="link"><a href="http://stop.glicer.com/no-exist.html" class="error tooltip" data-tooltip="Must exist (Http get error)">http://stop.glicer.com/no-exist.html</a>0 -> index.html</div><br><br><br></body></html>'

/home/vokunju1/public_html/404checker/tests/GlLinkCheckerTest.php:166

FAILURES!
Tests: 7, Assertions: 14, Failures: 3.
Web server shutdown

**Comment by alesanchezr** [comment]
@emmanuelroecker this was fixed as well (in the same PR that you approved). The problem was that the link http://lyon.glicer.com/ was no longer returning 200.

**Comment by emmanuelroecker** [comment]
Indeed :ok_hand:
