### ISSUE TITLE
error when install

### ISSUE THREAD

**Issue by ravisvyas** [emmanuelroecker/php-linkchecker#2]
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/console suggests installing psr/log-implementation (For using the console logger)
symfony/console suggests installing symfony/lock ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package satooshi/php-coveralls is abandoned, you should avoid using it. Use php-coveralls/php-coveralls instead.
Writing lock file
Generating autoload files

**Comment by alesanchezr** [comment]
This is not really an error, just a warning. The package still works.

**Comment by emmanuelroecker** [comment]
:+1: Super !
